jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build --rm=false --tag "leon721/composetest:${CIRCLE_SHA1}" .
          docker run --rm -it --entrypoint python "leon721/composetest:${CIRCLE_SHA1}" -m unittest discover