jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t leon721/composetest:$CIRCLE_BRANCH . \
          docker push leon721/composetest:$CIRCLE_BRANCH